# Site wide configuration

<<<<<<< HEAD
<<<<<<< HEAD
title: Home
description: "My personal Website"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: http://cromanpa94.github.io/cromanpa
=======
=======
>>>>>>> mmistakes/master
title: "My Site"
description: "This is a description of my awesome site."
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url:
feed:
  path: atom.xml
<<<<<<< HEAD
>>>>>>> mmistakes/master
=======
>>>>>>> mmistakes/master

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: Cristian Román-Palacios
  email: cromanpa94@gmail.com
  bio: "Ph.D. student at Wiens Lab (UofArizona). Mainly interested on Macroevolution and trait evolution"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: +CristianRomanPalaciosn
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
